version: "2"
run:
  concurrency: 4
  go: "1.24"
linters:
  default: none
  enable:
    - errcheck
    - errname
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nilnesserr
    - revive
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      rules:
        - name: unused-parameter
          disabled: true
formatters:
  enable:
    - gofmt
