name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    strategy:
      matrix:
        goos: [linux, windows]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: golangci/golangci-lint-action@v7
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: amd64

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test
        run: go test -v -race -count=1 ./...
